* Installation with Nix

There are two recommended ways of installing webmacs:

1. Nix
2. pip/virtualenv

** Nix

Currently, the easiest way to install webmacs is via the [[https://nixos.org/nix/][Nix package
manager]]:

#+BEGIN_SRC bash
nix-env -i webmacs
#+END_SRC

*** Need more help with nix?

Nix is available for Linux, macOS and other Unix-like systems. Rest
assured that removing Nix (along with any packages installed using
Nix) is as easy as =rm /nix -rf=.

If you do not have Nix, install it. For details see
https://nixos.org/nix/manual/#chap-installation, but this step
approximates to

#+BEGIN_SRC bash
bash <(curl https://nixos.org/nix/install)
#+END_SRC

and will require you to provide a sudo password.

Look out for, and follow the instructions which will appear once
nix is installed, and which will look something like this:

#+BEGIN_SRC text
Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  . /home/yourusername/.nix-profile/etc/profile.d/nix.sh

in your shell.
#+END_SRC

If you don't spot this, the installation will appear to have failed.

Now you can use =nix-env= to install webmacs:

#+BEGIN_SRC bash
nix-env -i webmacs
#+END_SRC

For further details, see
https://nixos.org/nix/manual/#chap-quick-start.

*** working on webmacs with nix

The command

#+BEGIN_SRC bash
nix-shell -p webmacs
#+END_SRC

will drop you into a shell which makes available all the compilers and
libraries required to build and run webmacs, thus =nix-shell= plays
the role of =virtualenv= in the pip/virtualenv approach described
below. Unfortunately, some of the libraries required to run the
tests, are not yet available in this shell.
